project:
  type: website
  output-dir: "docs"

website:
  navbar:
    background: primary
    title: "PECE Public Presentations"
    right:
      - text: "Talks"
        href: talks.html
      - text: "Workshop Materials"
        href: workshop-materials.html

format:
  html:
    theme: flatly
    css: "css/custom.css"
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
    highlight: tango
    lib_dir: libs


